# Generated by Django 2.1 on 2020-12-23 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lastname', models.CharField(max_length=200, unique=True, verbose_name='nom')),
                ('Firstname', models.CharField(max_length=200, unique=True, verbose_name='prénom')),
                ('Extern', models.BooleanField(default=False, verbose_name='externe ?')),
                ('Society', models.CharField(max_length=200, unique=True, verbose_name='société')),
            ],
            options={
                'verbose_name': 'Collaborateurs',
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='nom')),
                ('commentary', models.CharField(max_length=250, unique=True, verbose_name='commentaire')),
            ],
            options={
                'verbose_name': 'Compétences',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom')),
                ('descritpion', models.CharField(max_length=250, unique=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Domaine',
            },
        ),
        migrations.CreateModel(
            name='ListInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10, unique=True, verbose_name='valeur')),
                ('commentary', models.CharField(max_length=250, unique=True, verbose_name='commentaire')),
            ],
            options={
                'verbose_name': 'Liste des intérêts',
            },
        ),
        migrations.CreateModel(
            name='ListLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10, unique=True, verbose_name='valeur')),
                ('commentary', models.CharField(max_length=250, unique=True, verbose_name='commentaire')),
            ],
            options={
                'verbose_name': 'Liste des niveaux',
            },
        ),
        migrations.CreateModel(
            name='ListWorkStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='nom')),
                ('commentary', models.CharField(max_length=250, unique=True, verbose_name='commentaire')),
            ],
            options={
                'verbose_name': 'Liste postes de travail',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom')),
                ('description', models.CharField(max_length=200, unique=True, verbose_name='description')),
                ('administrateur', models.BooleanField(default=False, verbose_name='administrateur ?')),
            ],
            options={
                'verbose_name': 'Profils',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lastname', models.CharField(max_length=200, unique=True, verbose_name='nom')),
                ('Firstname', models.CharField(max_length=200, unique=True, verbose_name='prénom')),
                ('login', models.CharField(max_length=200, unique=True, verbose_name='login')),
                ('password', models.CharField(max_length=50)),
                ('profil', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Profil')),
            ],
            options={
                'verbose_name': 'Utilisateurs',
            },
        ),
        migrations.AddField(
            model_name='competence',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Field'),
        ),
    ]
