# Generated by Django 2.1 on 2020-12-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='descritpion',
            new_name='description',
        ),
    ]
