# Generated by Django 2.1 on 2020-12-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201223_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listworkstation',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='nom'),
        ),
    ]
