# Generated by Django 2.1 on 2020-12-23 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201223_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='field',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Field'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='nom'),
        ),
    ]
